# Generated by Django 3.0.3 on 2020-05-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nvdemande', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='traitement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Traité', 'Traité'), ('Cloturé', 'Cloturé'), ('Sans Objet', 'Sans Objet')], default='En cours', max_length=120)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Nvdemande.Contact')),
            ],
        ),
    ]
